### PR TITLE
Enable IPv6

### PR DESCRIPTION
**Pull request by miguelangel-nubla**
These changes are needed in order to allow dual-stack connectivity.

### CODE REVIEW

**Comment by TECH7Fox** [comment]
Did you test this out by moving those files to `/config/asterisk/custom`?

Also, I think something went wrong. There are 2 `[transport-tcp]` now and you didn't add whitespaces between the sections.

**Comment by TECH7Fox** [comment]
Alright, looks good now.

Since this will go directly to main please update the version to **4.0.4** in `asterisk/config.yaml` and add the new update to `CHANGELOG.md`.

**Comment by TECH7Fox** [comment]
Thanks! It will merge when the tests succeed.

**Comment by TECH7Fox** [comment]
@tbrasser yeah there seems to be a problem with the build so we didn't push the image yet. See https://github.com/TECH7Fox/asterisk-hass-addons/issues/257

**Comment by tbrasser** [comment]
Yeah that tar.gz artifact seems to be corrupted upstream.

**Pull request merged**
