### PR TITLE
Security log + Dateformat at logger.conf template to work with Fail2ban

### PR DESCRIPTION
**Pull request by Bethaaca**
@TECH7Fox and @felipecrs, please, take a look at config.yaml and logger.conf.gtpl.

Refs: https://www.fail2ban.org/wiki/index.php/Asterisk
[Fail2ban + logger.conf configurable #178](https://github.com/TECH7Fox/asterisk-hass-addons/issues/178)

### CODE REVIEW

**Comment by TECH7Fox** [comment]
We can't really change the **log_level** options because it's also used for other things.
Maybe a new option like **Security_messages** or something? (Maybe not the best naming but you get the point)

Rest looks good.

Btw, just for me, does fail2ban read the asterisk messages? I thought it would use the console.
Where do the messages even go?

**Comment by felipecrs** [comment]
> Maybe a new option like Security_messages or something? (Maybe not the best naming but you get the point)

Are these logs annoying? If they aren't much perhaps we can add this by default without any option.

**Comment by TECH7Fox** [comment]
> Are these logs annoying? If they aren't much perhaps we can add this by default without any option.

Not sure. Maybe if you get a lot of bots from different ip's? But if they are going to messages, the user won't notice them anyways right?

Maybe we should add `security` to some higher log levels. Like from `info` to `trace`?

**Comment by Bethaaca** [comment]
@TECH7Fox 
> We can't really change the **log_level** options because it's also used for other things. Maybe a new option like **Security_messages** or something? (Maybe not the best naming but you get the point)
> 
> Rest looks good.

Yeah, that´s good. 


> Btw, just for me, does fail2ban read the asterisk messages? 

I think do so. 

> I thought it would use the console. Where do the messages even go?

Maybe this path?

First link: 
[; Directory for log files is configures in asterisk.conf
; option astlogdir](https://github.com/asterisk/asterisk/blob/master/configs/samples/logger.conf.sample#L177:~:text=%3B%20Directory%20for%20log,%3B%20option%20astlogdir)

Second link: 
[astlogdir => /var/log/asterisk](https://github.com/asterisk/asterisk/blob/master/configs/samples/asterisk.conf.sample#:~:text=astlogdir%20%3D%3E%20/var/log/asterisk)

@felipecrs 
> Are these logs annoying? If they aren't much perhaps we can add this by default without any option.

My miniPC (8GB / 128GB) even crashed due to brute force attack.


> Maybe we should also add security to some higher log levels. Like from info to trace?

It might be like that, and there is another option:

[security.log => security](https://github.com/asterisk/asterisk/blob/master/configs/samples/logger.conf.sample#L177:~:text=security.log%20%3D%3E%20security)

A security file could be generated in the folder, couldn't it?

**Comment by TECH7Fox** [comment]
> My miniPC (8GB / 128GB) even crashed due to brute force attack.

So ,because the security messages got in the console it crashed when you got brute forced because of the amount of logs? 
Then we should probably not include it if it is that many messages right?

> A security file could be generated in the folder, couldn't it?

Yeah, but if fail2ban needs to read those updated files we first need to make a symlink from the log file to something like `/config/asterisk/logs`. Then we could also always keep that enabled since it doesn't use the console at all.

**Comment by Bethaaca** [comment]
> So ,because the security messages got in the console it crashed when you got brute forced because of the amount of logs? Then we should probably not include it if it is that many messages right?

It could be like that too.

> Yeah, but if fail2ban needs to read those updated files we first need to make a symlink from the log file to something like `/config/asterisk/logs`. Then we could also always keep that enabled since it doesn't use the console at all.

Nice, I got it.

Off: [We can integrate HA and Fail2ban](https://www.home-assistant.io/integrations/fail2ban/)

**Comment by felipecrs** [comment]
Guys, let's please try to have this finished for 3.0.0.

**Pull request closed without merging**
