### PR TITLE
Add option to download additional sounds languages

### LINKED ISSUE #117: Custom wait music for parking
It would be nice to be able to edit the music what is played when parking a call.

### PR DESCRIPTION
**Pull request by felipecrs**
- Closes #117

### CODE REVIEW

**Comment by felipecrs** [comment]
@TECH7Fox this is a completely different take than #155.

While we could probably reduce the add-on size by not even bundling the core English sounds as suggested by @nanosonde, this is a different thing and could be implemented later.

**Comment by felipecrs** [comment]
Since the add-on now has access to `/media`, users can customize their Asterisk configuration files to point to whatever music they have stored in `/media`, like as [mentioned](https://github.com/TECH7Fox/asterisk-hass-addons/issues/117#issuecomment-1065248649) by @nanosonde.

**Review by TECH7Fox — APPROVED** [review]
Looks good. How will it handle moh?

**Comment by felipecrs** [comment]
> How will it handle moh?

It won't, moh will still be included by default in the image. At least ATM.

**Pull request merged**
