### PR TITLE
Fix asterisk not starting after 2.0.0

### PR DESCRIPTION
**Pull request by felipecrs**
Just don't ask me why, neither how. But please tell me if you know.

Thanks for the [hint](https://github.com/TECH7Fox/asterisk-hass-addons/issues/127#issuecomment-1069648440), @nanosonde.

### CODE REVIEW

**Comment by felipecrs** [comment]
@TECH7Fox I tested this already two times, I can confirm it fixes the issue. The PR requires your approval, so if you could please approve and merge I would appreciate. Thanks!

**Review by TECH7Fox — APPROVED** [review]
Sorry for the wait, was sleeping.

**Comment by TECH7Fox** [comment]
Don't forget the version in config

**Comment by felipecrs** [comment]
> Don't forget the version in config

lol thank you. Done.

**Review by TECH7Fox — APPROVED** [review]

**Pull request merged**
