### PR TITLE
Temp fix for build

### LINKED ISSUE #257: CI failing
@felipecrs you have any idea?
Haven't made a release yet so that's still fine.

### PR DESCRIPTION
**Pull request by miguelangel-nubla**
Fixes #257

### CODE REVIEW

**Comment by TECH7Fox** [comment]
Build still fails. Are they aware of the issue upstream? Maybe they are already working on a fix.

**Comment by miguelangel-nubla** [comment]
```
failed to push ghcr.io/tech7fox/asterisk-hass-addon: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```
Build is fixed, now it is failing to publish the build to ghcr.io. Did you touch the actions token recently? Maybe it has expired? You can check them at https://github.com/settings/tokens and https://github.com/TECH7Fox/asterisk-hass-addons/settings/secrets/actions

Else you can force retry the build again, may be a temporary issue with the authorization flow.

**Comment by TECH7Fox** [comment]
Ah, yes I don't think that the secrets are available in a PR. Suprised that it tried to deploy anyway.

**Comment by TECH7Fox** [comment]
Ah I see. 

I think that only works on our own PR's. Secrets aren't passed to PR's from forks.

**Comment by felipecrs** [comment]
Just to mention that this was fixed in upstream by https://github.com/asterisk/asterisk/commit/1bf6d02f13ea06369f2b0b948d4ad69c3b3cf5bd. We should revert when upgrading to a version of Asterisk which contains this commit.

**Pull request merged**
