### PR TITLE
Add STDIN service

### PR DESCRIPTION
**Pull request by felipecrs**
Refs:

- Fixes https://github.com/TECH7Fox/asterisk-hass-addons/issues/148
- https://github.com/TECH7Fox/asterisk-hass-addons/pull/150
- https://github.com/TECH7Fox/asterisk-hass-addons/pull/154#issuecomment-1159795570

### CODE REVIEW

**Comment by TECH7Fox** [comment]
Alright should be working now. Used the same way the SSH add-on used to read stdin.

@felipecrs could you test this again? I tried using GH codespaces but it gives me a `400: Bad Request`. 😢 Maybe I should just build a linux devserver...

**Comment by felipecrs** [comment]
> @felipecrs could you test this again? I tried using GH codespaces but it gives me a 400: Bad Request. 😢 Maybe I should just build a linux devserver...

If you are on Windows, you can use WSL2. That's what I do. I build the image on my WSL2, on Windows, like:

```console
docker build asterisk --tag ghcr.io/felipecrs/asterisk-hass-addon:latest --push
```

Then, in my HA, I change `config.yaml` as follows:

```diff
name: Asterisk
- version: 2.2.0
+ version: latest
slug: asterisk
description: PBX server for SIP devices like doorbells and phones
url: https://github.com/TECH7Fox/asterisk-hass-addons
- image: "ghcr.io/tech7fox/{arch}-addon-asterisk"
+ image: "ghcr.io/felipecrs/asterisk-hass-addon"
```

And it works. Something else you can do is to build it inside of HA as well using the SSH add-on:

```console
DOCKER_BUILDKIT=1 docker build asterisk
```

**Comment by felipecrs** [comment]
But I'm trying it here now.

**Comment by felipecrs** [comment]
I tested here, for me it does not work still. The stdin service only keeps restarting every second.

**Comment by TECH7Fox** [comment]
I'm not sure why it's not working. I looked at other add-ons and there it's working fine.
Any ideas?

* [ssh add-on](https://github.com/hassio-addons/addon-ssh/blob/96bccd1aa6b7a65f969a5eb610ffe78de9740736/ssh/rootfs/etc/services.d/stdin/run)
* [rpc shutdown add-on](https://github.com/home-assistant/addons/blob/master/rpc_shutdown/data/run.sh)

Btw, I'm working on a linux system to test these things properly. Couldn't get Github codespaces working because HA gives a HTTP reverse proxy error.

**Comment by TECH7Fox** [comment]
Tried some more, but can't get it to work. Always restarts.
Don't understand why though. The ssh add-on had the excact same like this. And other add-ons just have the `run.sh`.
They did remove it. Maybe something changed? [Remove STDIN PR](https://github.com/hassio-addons/addon-ssh/pull/349/files).

**Comment by felipecrs** [comment]
I guess we need to find some examples which are already using S6 Overlay 3.x.

**Comment by felipecrs** [comment]
Tested, works!

**Comment by TECH7Fox** [comment]
Ah great you got it working! Smart to put it straight into the Asterisk CLI. Didn't think about that.

**Pull request merged**
