### PR TITLE
Release 4.3.0

### PR DESCRIPTION
**Pull request by felipecrs**

### CODE REVIEW

**Comment by felipecrs** [comment]
@TECH7Fox, just to let you know I am not planning on continuing maintaining after this release. I personally lost the interest on Asterisk and prefer using alternatives like go2rtc for 2-way audio.

**Comment by TECH7Fox** [comment]
> @TECH7Fox, just to let you know I am not planning on continuing maintaining this add-on after this release. I personally lost the interest on Asterisk and prefer using alternatives like go2rtc for 2-way audio.

I understand. Thank you for all your help with this project! Hope to see you around on Discord and forums. 🫡

**Comment by felipecrs** [comment]
> > @TECH7Fox, just to let you know I am not planning on continuing maintaining this add-on after this release. I personally lost the interest on Asterisk and prefer using alternatives like go2rtc for 2-way audio.
> 
> I understand. Thank you for all your help with this project! Hope to see you around on Discord and forums. 🫡

Turns out I will probably continue maintaining it for the foreseeable future, as I didn't manage to entirely [get rid of Asterisk in my setup](https://github.com/felipecrs/dahua-vto-on-home-assistant/issues/1).

I just unsubscribed from issues notifications to reduce the burden a little bit.

**Comment by felipecrs** [comment]
Also, I have good news to share:

This add-on can now be built directly in Home Assistant through Supervisor, as I added support for Buildkit in Supervisor (https://github.com/home-assistant/supervisor/pull/5974).

This makes it a lot simpler to test changes to it.

**Pull request merged**
