### PR TITLE
Prefer Opus over other codecs

### PR DESCRIPTION
**Pull request by OnFreund**
Opus is a superior codec to the other. Since most devices support ulaw and alaw, listing Opus after them means it will never be picked. This PR lists it first so it will be picked when available.

### CODE REVIEW

**Comment by felipecrs** [comment]
I wonder if we should not add opus to chan_sip as well:

https://github.com/TECH7Fox/asterisk-hass-addons/blob/deee07bb6fc0261f374daad9ae8b1c69da659aae/asterisk/rootfs/usr/share/tempio/sip_default.conf.gtpl

@TECH7Fox, @bdherouville (https://github.com/TECH7Fox/asterisk-hass-addons/pull/199), @nanosonde do you guys have any idea why it's not there yet?

**Comment by OnFreund** [comment]
Yes, I've been working with it locally. I haven't tested the case where one of the parties doesn't support Opus, but the whole point of having multiple codes is to allow fallback.

**Comment by TECH7Fox** [comment]
> I wonder if we should not add opus to chan_sip as well:
> 
> https://github.com/TECH7Fox/asterisk-hass-addons/blob/deee07bb6fc0261f374daad9ae8b1c69da659aae/asterisk/rootfs/usr/share/tempio/sip_default.conf.gtpl
> 
> @TECH7Fox, @bdherouville (https://github.com/TECH7Fox/asterisk-hass-addons/pull/199), @nanosonde do you guys have any idea why it's not there yet?

No reason, I never considered it.

**Comment by OnFreund** [comment]
Any chance we can get a release with this any time soon?

**Pull request merged**
