### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by TECH7Fox**

### CODE REVIEW

**Comment by TECH7Fox** [comment]
@felipecrs could you test this? It seems like my HA on raspberry doesn't like building the container.

**Comment by felipecrs** [comment]
@TECH7Fox I will test this later today.

**Comment by TECH7Fox** [comment]
@felipecrs did you get to test this? I think it should work, but maybe it will mess with the asterisk CLI.

**Comment by felipecrs** [comment]
Sorry, no. I current have little time :(

**Comment by felipecrs** [comment]
@TECH7Fox

image

It does not work for me. =/

**Review by felipecrs — APPROVED** [review]

**Pull request merged**
