### PR TITLE
Embed build script in the dockerfile

### PR DESCRIPTION
**Pull request by felipecrs**
So that we leverage docker build cache a bit more.

### CODE REVIEW

**Comment by felipecrs** [comment]
@nanosonde can you please check this?

**Comment by nanosonde** [comment]
@felipecrs Have you tested this already?
The DESTDIR env var is now set globally also for the normal “make all”.
The trick is to run “make all” without DESTDIR and only run „make install“ and „make samples“ with DESTDIR set.

I have to check the Makefile again.

**Comment by felipecrs** [comment]
Ops, I didn't mean to change what's working. Fixed. Can you check again @nanosonde?

**Comment by nanosonde** [comment]
I needed some sleep. ;-)

As you merged it already >I have tested everything again with the whole develop branch.

BTW: How you test your changes locally?

**Comment by felipecrs** [comment]
> BTW: How you test your changes locally?

Currently I'm building in my home's Home Assistant. I checkout the code there and keep rebuilding.

But I use the SSH addon to rebuild (`cd /addons/asterisk-hass-addons && docker build asterisk`) so at least I know what's happening. Then, when I click to rebuild from the addon page, it rebuilds quickly thanks to the build cache.

Don't forget to comment out the `image` line in config.yaml, and also, if you make changes to config.yaml, HA may struggle to pick them, so make sure to always bump the version to ensure HA will pick up changes to config.yaml.

**Pull request merged**
